before_install:
  - pip install jieba3k coveralls nltk
  - python -m nltk.downloader -d ~/nltk_data punkt


language: python
python:
  - "3.6"

cache:
  pip: true

install:
- "git clone -b dashboard https://github.com/zeeguu-ecosystem/Zeeguu-API.git api"
- "cd api"
- "python setup.py develop"