 language: python

 cache:
   pip: true

python:
  - "3.6"

env:
  - FLASK_APP=main.py

install:
  - pip install -r zeeguu_dashboard/requirements.txt

script:
  - "pushd zeeguu_dashboard/"
  - "python app/test_foo.py"
  - "popd"